### ISSUE TITLE
[Feature]: Hotkey / F3 Menu additionals  

### ISSUE THREAD

**Issue by FatCodeNerd** [TheButterbrotMan/Deathdusk#139]
### Is your feature request related to a problem? Please describe.

Two issues
1) Can't see the coordinates of where I am, only chunk coordinates. The XYZ to clarify. F3 Menu is huge but nowhere I can see
2) Wish the chests had the 'organize' button to sort items, same with inventory and other such inventories

### Describe the solution you'd like

Add the ability to sort inventories with a button in the inventory GUI, as well as make coordinates visible to see 

### Additional context

n/a

**Comment by TheButterbrotMan** [comment]
Please checkout the quest book for an alternative way on getting coordinates. You can add this mod if you wanna sort your inventory: https://www.curseforge.com/minecraft/mc-mods/inventory-sorting. I will not add him to the modpack because he is incompatible to some modded guis and overlap there weirdly.
