### ISSUE TITLE
[Feature]: Apotheosis port for farbic - enough said

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#68]
### Is your feature request related to a problem? Please describe.

Modular and selectable modules to improve various aspects, from enchanting to blocks, to mob difficulty to other stuff

### Describe the solution you'd like

https://www.curseforge.com/minecraft/mc-mods/apotheosis-fabric

**Comment by Ginger0Ray** [comment]
+1 Enough' said

**Comment by TheButterbrotMan** [comment]
I will need to review this modules, that will take some time. This will be not in the next updates, but somewhen in the future.

**Comment by TheButterbrotMan** [comment]
Hmm, i dont know if this mod is worth it. Basically all modules are covered by other mods. Opinions?

**Comment by Butamichi** [comment]
I don't think most modules will even work to be honest, the enchantment module brings new enchantments that are interesting but in my opinion you will have to make the enchanting table not crafteable to mantain the current enchantment system, the villager module and MCA can be a problem if they conflict but if not it can be another improvement on villages, the garden module its just great, not because of the plant heigh limit but because it makes animal transport a thing, so we can collect all the animals on the pack, the potion charms are pretty much useless thanks to trinkets and jujus and the spawner module have a better version already in the modpack. If I where to add this I would only add the Garden Module and maybe, if its not to much work the enchantment one only because the enchantments, they are more or less as op as anything we already have so it should be balanced in the current state of the pack.

**Comment by TheButterbrotMan** [comment]
I am agreeing on @Butamichi opinion. So ill close this for now.
