### ISSUE TITLE
[Feature]: Origins

### ISSUE THREAD

**Issue by Ginger0Ray** [TheButterbrotMan/Deathdusk#73]
### Is your feature request related to a problem? Please describe.

Origins mod

https://www.curseforge.com/minecraft/mc-mods/origins

### Describe the solution you'd like

Would be nice if it was added

**Comment by TheButterbrotMan** [comment]
I need a custom Origins mod for the modpack, when I have time to create this I will take it on. If you have suggestions for Origins, just post them here.

**Comment by Butamichi** [comment]
Necromancer

An Origin focused on the use of magic and summoning undead creatures. I Don't know how complicated you can make origins, I've seen some origins veeery mechanic heavy with different meters and transformations etc. so this is relatively simple I thing.  This should be a nice bases for this archetype, can be fleshed out with better summons or a way to have more than one at the same time etc. it depends on how complex you can make it really.

Skill 1: Zombie warrior, summon a friendly Zombie equipped with chainmail and a stone axe to act as a tank.
Skill 2: Skelly archer, summon a skeleton equipped with leather armour ( primarily to avoid burning on sun )

Pros: Magic resistance and damage up, less damage received from undead mobs. Resistance to wither effect and infections.
Cons: Can only equip armour with a value of chainmail or less since its a mage, have permanent weakness II making physical damage less viable long term, villagers prices up ( like when you hit one) because necromancy is seen as a bad thing.

**Comment by Ginger0Ray** [comment]
Personally I have always liked things that have had an elytra with debuffs like less max health and must eat a lot

**Comment by TheButterbrotMan** [comment]
Due to having MCA Reborn at the moment, and maybe some destination mod later, i will close this for now.
