### ISSUE TITLE
[Feature]: QoL Bad to the bone baubles

### ISSUE THREAD

**Issue by Ginger0Ray** [TheButterbrotMan/Deathdusk#95]
### Is your feature request related to a problem? Please describe.

The fact that Glasses from bad to the bone take up the helmet slot when we have baubles is pretty frustrating

### Describe the solution you'd like

It would be nice if it was added to the tags of baubles and able to be put in the glasses slot

**Comment by Evviedawn** [comment]
Agreed. And maybe the Bad to the Bone effects not happen so often? They are more of a regular thing happening every few minutes, instead of a occasional effect that happens. 

Currently there is no point in making and wearing a helmet, since you have to keep the glasses on almost 24/7. If you were to allow them to be in the glasses slot instead, I'm sure players would just wear a helmet and glasses 24/7 and not worry about the effect anymore. Making it pointless to even have it in the first place. 

At first the mod was interesting and silly. But after about 10minutes of playing it was just annoying to try to do anything. I feel like this could be fixed by making the effects not happen as often. Making them more random and less probable/predictable.

**Comment by ArtixAllMighty** [comment]
the config options definitely allow for the effects to be spaced out more.
ive never been hot on baubles or curios, but i'd probably need to start looking into it. 
although evviedawn does have a point, if you can just chug em in another slot, the handicap isn't even relevant anymore.
