### ISSUE TITLE
[Feature]: About new content.

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#97]
### Is your feature request related to a problem? Please describe.

About adding to much to fast.

### Describe the solution you'd like

I think the pack needs one or two updates that don't add anything but instead flesh out existing thinks, polish bugs and balances the game. 

I'm loving this pack, im no coder no artist no dev, but I know a pack like this is a lot of ungratful work for free most of time, and that is why I understand that all takes lots of time BUT, its also because of this that I thinks its better to stop adding new things after 2.0.9 for a time and make what is already here work to its full potential.

Quest book its still mostly empty, in a pack this big that is a problem that affects a lot the player expirience.
Lots of mods im sure are redundant or just don't make the game as enjoyable as you as the dev want.
Balance is a problem, ej: I will never craft vanilla armor as the plates needed are to much of a material sink when gem armor its better an cheaper.
Economy is none existant, yes the money is there but you can do nothing with it. Maybe change waystone cost from exp to 3 silver if possible, remove money from loot chest and  leave it only to villagers and repetable Quest from the quest book. Add a shop to the Questbook to the make money flow. Try to make players more inclined to trade betwen them.
Server rules are still barebones, is it RP? How much? I love the idea of the RP but if its official then lets make a simple character sheet for all active user to make their characters official on Discord. That will also give you ideas for Origins.

My point is as follows, the pack and people behind it are great, I do want a giant pack with a thausand hours worth of content right now, but its better in my humble opinion to first finish the basics, heck may be look for more staff to help with all of it. People than want all the mods in a pack go for All the mods number whatever, don't make it a kitchen sink pack pls, make it the medieval Rpg with personality it seems to want to be.

### Additional context

Srry for my shittie english its not my first lenguage, and I learned on my own so my grammar an spelling are bad.

**Comment by wildficus** [comment]
I volunteer to flesh out such things , will become a lot more available after 7th July where I  can provide a lot of help with such improvements

**Comment by TheButterbrotMan** [comment]
With each update, I fix things and add new things. This is because the modpack is still in beta at the moment. I try to put as much content as possible, because it will be hard to make big changes after the first release. 

The questbook unfortunately takes a lot of time that I don't have right now, if you are interested in filling it faster I suggest you help me. 
It can be for sure that some items are duplicated or redundant, that's why this GitHub exists, so you can tell me.  

Economy does not exist because it needs player interaction. I can't force anyone to do player interaction. I can't change the waystone costs or remove the money from the Loot Chests. A store for the questbook is in the works (when I have time).

The last version of the server unfortunately showed that a "character sheet" doesn't really bring a change, because everyone does what they feel like anyway. For this reason we have changed to a model where you can do what you want within the city. Only the mayor is responsible. Outwardly, RP should be done. 

If there are ideas for Origins, please also post them on GitHub.

It's hard to finalize the basics without enough feedback and time. Also you can't compare this modpack with "All The Mods", completely different goals and completely different content. If you have suggestions that destroy the medieval mood post them on GitHub.

Translated with www.DeepL.com/Translator (free version)

**Comment by TheButterbrotMan** [comment]
For example, you could make quests and send them to me, or at least write in #53 ideas.
